/**
 * 記事からYouTube Shorts用の台本・タイトル・説明文を自動生成する
 * 使い方: npx tsx youtube-script.ts [genreId]
 * → scripts/<genreId>/<date>-<title>.md に保存
 *
 * 次のステップ: 生成した台本をVOICEVOX等のTTSで音声化 → CapCut等で動画化
 */
import "dotenv/config";
import Anthropic from "@anthropic-ai/sdk";
import * as fs from "fs";
import { GENRES, getGenreById, getTopicForGenre } from "./genres.js";

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

interface YoutubeScript {
  videoTitle: string;
  description: string;
  hashtags: string[];
  script: string; // 台本（60秒以内に読めるテキスト）
  thumbnailText: string; // サムネイルに表示する短いテキスト
}

async function generateYoutubeScript(genreId: string): Promise<void> {
  const genre = getGenreById(genreId);
  if (!genre) {
    console.error(`ジャンルが見つかりません: ${genreId}`);
    process.exit(1);
  }

  const topic = getTopicForGenre(genre);
  console.log(`🎬 YouTube Shorts 台本生成中: ${genre.name}`);
  console.log(`   テーマ: ${topic}`);

  const prompt = `あなたは${genre.writerPersona}です。
以下のテーマでYouTube Shorts（縦型・60秒以内）の台本を作成してください。

テーマ: ${topic}

【台本の要件】
- 読了時間: 55〜60秒（日本語は1分で約300文字）
- 構成:
  1. 冒頭3秒: 「〇〇で悩んでいる人必見！」のような強烈なフック
  2. 問題提起（10秒）: 視聴者の悩みを具体的に描写
  3. 解決策（30秒）: 3つのポイントを簡潔に説明
  4. まとめ（10秒）: 要点を1文で
  5. CTA（7秒）: 「詳しくはプロフィールのリンクへ！」＋チャンネル登録促進

【重要】
- 文語でなく口語（話し言葉）で書く
- 数字を積極的に使う（「3つ」「10万円」「30日で」等）
- 改行は読みやすさのため1文ごとに入れる

以下のJSON形式で返してください:
{
  "videoTitle": "【タイトル】〇〇で△△する方法（30文字以内）",
  "description": "YouTube動画説明文（150文字）#ハッシュタグ含む",
  "hashtags": ["タグ1", "タグ2", "タグ3", "タグ4", "タグ5"],
  "script": "台本テキスト（300文字前後）",
  "thumbnailText": "サムネイルに載せる短文（15文字以内）"
}`;

  const response = await client.messages.create({
    model: "claude-haiku-4-5",
    max_tokens: 2048,
    messages: [{ role: "user", content: prompt }],
  });

  const text = response.content[0].type === "text" ? response.content[0].text : "";
  const jsonMatch = text.match(/\{[\s\S]*\}/);
  if (!jsonMatch) throw new Error("生成失敗");

  const result: YoutubeScript = JSON.parse(jsonMatch[0]);

  const date = new Date().toISOString().split("T")[0];
  const safeTitle = result.videoTitle.slice(0, 20).replace(/[\/\\:*?"<>|【】]/g, "");
  const dir = `scripts/${genre.id}`;
  fs.mkdirSync(dir, { recursive: true });
  const filename = `${dir}/${date}-${safeTitle}.md`;

  const output = `# ${result.videoTitle}

## サムネイルテキスト
${result.thumbnailText}

## 動画説明文
${result.description}

## ハッシュタグ
${result.hashtags.map((h) => `#${h}`).join(" ")}

## 台本
${result.script}

---
*Generated by auto-income | ${date}*
`;

  fs.writeFileSync(filename, output);
  console.log(`✅ 台本を保存: ${filename}`);
  console.log(`   タイトル: ${result.videoTitle}`);
  console.log(`   サムネイル: ${result.thumbnailText}`);
}

// 全ジャンル or 指定ジャンル
const targetIds = process.argv[2] ? [process.argv[2]] : GENRES.map((g) => g.id);

(async () => {
  for (const id of targetIds) {
    await generateYoutubeScript(id).catch((e) =>
      console.error(`❌ ${id}: ${e.message}`)
    );
    if (id !== targetIds[targetIds.length - 1]) {
      await new Promise((r) => setTimeout(r, 5000));
    }
  }
  console.log(`\n🎉 完了！ scripts/ フォルダに台本が保存されました`);
})();
